sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
notifications:
  email: false
install:
  # Requirements needed for Travis CI
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install coverage
script: coverage run --include print_data.py -m unittest discover
after_success: coveralls
